apiVersion: apps/v1
kind: Deployment
metadata:
  name: verge-risk-engine
  namespace: verge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verge-risk-engine
  template:
    metadata:
      labels:
        app: verge-risk-engine
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: risk-engine
          image: verge-risk-engine:0.3.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: verge-config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command:
            - python
            - -m
            - verge_risk
            - --redpanda
            - redpanda:9092
            - --topic
            - verge.events
            - --post
            - http://verge-api:8000
